version: '3'
services: 
   postgres:        # postgres service 
     image: 'postgres:latest'
     environment: 
          - POSTGRES_PASSWORD=postgres_password
   redis:           # redis service 
     image: 'redis:latest' 
   api:          # server service 
     build: 
        dockerfile: dockerfile.dev
        context: ./server
     volumes: 
        - /app/node_modules
        - ./server:/app  
     environment:   # specify environmnt variables 
        - REDIS_HOST=redis # from the redis service above 
        - REDIS_PORT=6379      # from the redis documentation 
        - PGUSER=postgres
        - PGHOST=postgres
        - PGDATABASE=postgres
        - PGPASSWORD=postgres_password
        - PGPORT=5432

   client: 
      build: 
         dockerfile: dockerfile.dev
         context: ./client
      volumes:
         - /app/node_modules
         - ./client:/app
   

   worker: 
      build:
        dockerfile: dockerfile.dev
        context: ./worker
      volumes:
         - /app/node_modules
         - ./worker:/app      
   

   nginx:
      depends_on:
              - api
              - client      
      restart: always
      build: 
         dockerfile: dockerfile.dev
         context: ./nginx
      ports: 
         - '3050:80'   
